- name: Security Patching
  hosts: all
  become: yes
  tasks:
    - name: Update all packages to the latest version
      apt:
        upgrade: dist
        update_cache: yes

    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Reboot instance if required
      reboot:
        msg: "Reboot initiated by Ansible for security patching"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists
